# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-07 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapesc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='permissao',
            field=models.CharField(default=b'S', max_length=128),
        ),
        migrations.AddField(
            model_name='imagem',
            name='permissao',
            field=models.CharField(default=b'N', max_length=128),
        ),
    ]
