# Generated by Django 2.2.4 on 2019-09-30 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fapesc', '0011_auto_20190903_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='comunidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fapesc.comunidade'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fapesc.usuario'),
        ),
    ]
