# Generated by Django 2.2.4 on 2019-09-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapesc', '0015_auto_20190930_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='lati',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='historico',
            name='longe',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
