# Generated by Django 2.2.5 on 2019-12-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fapesc', '0017_historico_dataimagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
